root: ./

redirects:
  getting-started: README.md
  configuration-parameters: getting-started/installation/configuration-parameters/README.md
  configuration-reload: getting-started/installation/configuration-parameters/configuration-reload.md
  workspaces: getting-started/installation/configuration-parameters/workspaces.md
  methods-and-events: getting-started/installation/methods-and-events.md
  authorization-process: getting-started/installation/authorization-process-in-detail.md
  how-the-uid-parameter-works: readme/installation/how-the-uid-parameter-works.md
  set-up-two-factor-authentication: getting-started/installation/set-up-two-factor-authentication.md
  naming-conventions: getting-started/installation/naming-conventions.md
  building-emails: email-builder.md
  page-builder-overview: page-builder/README.md
  embedding-videos-in-a-page: page-builder/embedding-videos-in-a-page.md
  popup-builder-overview: popup-builder/README.md
  testing-and-integrating-popup-builder: popup-builder/testing-and-integrating.md
  setting-layout-and-size-popup-builder: popup-builder/setting-layout-and-size/README.md
  advanced-settings-popup-builder: popup-builder/setting-layout-and-size/advanced-settings.md
  file-manager-overview: file-manager-application-overview.md
  server-side-options: server-side-options/README.md
  toolbar-options: server-side-options/toolbar-options.md
  storage-options: server-side-options/storage-options/README.md
  configure-your-aws-for-bee: server-side-options/storage-options/configure-your-aws-s3-bucket.md
  connect-your-own-file-storage: server-side-options/storage-options/connect-your-file-storage-system.md
  content-options: server-side-options/content-options.md
  services-options: server-side-options/services-options.md
  undo-changes-history: server-side-options/undo-and-changes-history.md
  special-links-merge-tags: advanced-options/special-links-and-merge-tags.md
  content-dialog: advanced-options/content-dialog.md
  custom-color-palette: advanced-options/custom-color-palette.md
  font-management: advanced-options/font-management.md
  roles-and-permissions: advanced-options/roles-and-permissions.md
  smart-merge-tags: advanced-options/smart-merge-tags.md
  commenting: advanced-options/commenting.md
  custom-attributes: advanced-options/custom-attributes.md
  meta-tags: advanced-options/meta-tags.md
  custom-languages: advanced-options/custom-languages.md
  display-conditions: advanced-options/display-conditions.md
  advanced-permissions: advanced-options/advanced-permissions.md
  custom-file-picker: advanced-options/custom-file-picker.md
  custom-headers: advanced-options/custom-headers.md
  content-defaults: appearance/content-defaults.md
  custom-sidebar-position: appearance/custom-sidebar-position.md
  content-tile-sorting: appearance/content-tile-sorting.md
  content-tile-grouping: appearance/content-tile-grouping.md
  loading-spinner-theme: appearance/loading-spinner-theme.md
  custom-tab-layout: appearance/custom-tab-layout.md
  custom-look-feel: appearance/themes.md
  custom-css: appearance/custom-css.md
  custom-rows: custom-rows/understanding-custom-rows.md
  how-it-works: custom-rows/how-it-works.md
  loading-custom-rows-from-your-ui: custom-rows/loading-custom-rows-from-your-ui.md
  displaying-saved-rows: custom-rows/displaying-saved-rows.md
  generating-custom-rows-from-existing-content: custom-rows/generating-custom-rows-from-existing-content.md
  extending-custom-rows-with-content-dialog: custom-rows/extending-custom-rows-with-content-dialog.md
  save-rows: saved-rows/save-rows-overview.md
  save-rows/video-how-to-implement-save-rows: saved-rows/save-rows-video-tutorial.md
  save-rows/edit-single-row-mode: saved-rows/edit-single-row-mode.md
  save-rows/synced-rows: saved-rows/synced-rows.md
  working-with-forms: custom-rows/displaying-saved-rows.md
  passing-forms-to-the-builder: form-block/integrating-and-using-the-form-block/passing-forms-to-the-builder.md
  form-structure-and-parameters: form-block/integrating-and-using-the-form-block/form-structure-and-parameters.md
  allowed-form-fields: form-block/integrating-and-using-the-form-block/allowed-form-fields.md
  amp-carousel: amp-for-email.md
  addons: addons/addons-overview.md
  custom-addons: addons/custom-addons/README.md
  addon-development: addons/custom-addons/addon-development.md
  addon-development-vendor: addons/partner-addons/README.md
  partner-addons-directory: addons/partner-addons/partner-addons-directory.md
  using-addons: addons/partner-addons/installing-partner-addons.md
  openai-addon-customization: addons/partner-addons/openai-addon/README.md
  open-ai-and-data-security: addons/partner-addons/openai-addon/open-ai-and-data-security.md
  alternate-text-generation-with-ai: addons/partner-addons/alternate-text-generation-with-ai.md
  addons-developer-faq: addons/addon-faqs.md
  co-editing: collaborative-editing.md
  mobile-design-mode: mobile-design-mode.md
  tracking-message-changes: tracking-message-changes.md
  message-services-api: content-services-api/csapi-overview.md
  template-catalog-api: template-catalog-api.md
  message-services-api-reference: content-services-api/content-services-api-reference.md
  msapi-pricing-faqs: content-services-api/faqs.md
  multilanguage-templates: multi-language-templates.md
  error-management: error-management/onwarning.md
  editor-errors: error-management/beefree-sdk-editor-errors.md
  file-system-provider-errors: error-management/file-system-provider-errors.md
  json-parser-errors: error-management/json-parser-errors.md
  template-validation-and-update: error-management/template-validation-and-update.md
  template-validation-errors: error-management/template-validation-and-update-errors.md
  sample-code: sample-code.md
  scheduled-maintenances: scheduled-maintenances.md
  builder-addons/addons/partner-addons/openai-addon: builder-addons/addons/partner-addons/ai-writing-assistant.md
  builder-addons/addons/partner-addons/openai-addon/open-ai-and-data-security: builder-addons/addons/partner-addons/ai-writing-assistant/data-security.md
  builder-addons/addons/partner-addons/openai-addon/ai-generated-meta-tag-fields: builder-addons/addons/partner-addons/ai-writing-assistant/ai-generated-meta-tag-fields.md
  builder-addons/addons/partner-addons/openai-addon: builder-addons/addons/partner-addons/ai-writing-assistant/token-upselling.md
  rows/custom-rows: rows/reusable-content/create/pre-build.md
  rows/custom-rows/understanding-custom-rows: rows/reusable-content/create/pre-build.md
  rows/custom-rows/how-it-works: rows/reusable-content/create/pre-build/implement-custom-rows.md
  rows/custom-rows/loading-custom-rows-from-your-ui: rows/reusable-content/create/pre-build/implement-custom-rows.md
  rows/custom-rows/displaying-saved-rows: rows/reusable-content/create/save/implement-self-hosted-saved-rows.md
  rows/custom-rows/generating-custom-rows-from-existing-content: rows/reusable-content.md
  rows/custom-rows/extending-custom-rows-with-content-dialog: rows/reusable-content.md
  rows/saved-rows: rows/reusable-content/create/save.md
  rows/saved-rows/save-rows-overview: rows/reusable-content/create/save.md
  rows/saved-rows/save-rows-video-tutorial: rows/reusable-content/create/save/implement-self-hosted-saved-rows.md
  rows/saved-rows/edit-single-row-mode: rows/reusable-content/sync/initialize-edit-single-row-mode.md
  rows/saved-rows/synced-rows: rows/reusable-content/sync/implement-synced-rows.md
