openapi: 3.0.0
info:
  title: Get a Category
  description: Retrieve a specific category in the catalog.
  version: 1.0.0
servers:
- url: https://api.getbee.io
  description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Enter Dev Console API Key as Bearer token
paths:
  /v1/catalog/categories/:slug:
    get:
      summary: Get a Category
      description: Retrieve a specific category in the catalog.
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example:
                  bg_color: '#F8F8F8'
                  fb_color: '#333A45'
                  highlighted: false
                  icon: null
                  id: fashion-week
                  image: null
                  name: Fashion Week
                  description: Strut into the spotlight of style with our Fashion
                    Week email templates. Whether you're unveiling a new collection
                    or promoting exclusive runway-inspired deals, these templates
                    offer a chic and visually captivating platform to make your mark
                    during the most fashionable moments.
                  short_description: Stand out this Fashion Week with our email and
                    page templates
                  parent: seasonal
        '400':
          description: Bad request. The request could not be understood or was missing
            required parameters.
        '401':
          description: Unauthorized. Authentication is required and has failed or
            has not been provided.
        '403':
          description: Forbidden. The request was valid, but the server is refusing
            action.
        '500':
          description: Internal Server Error. An unexpected condition was encountered.