openapi: 3.0.0
info:
  title: Get a List of All Templates
  description: Retrieve a list of all templates in the catalog.
  version: 1.0.0
servers:
- url: https://api.getbee.io
  description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Enter Dev Console API Key as Bearer token
paths:
  /v1/catalog/templates:
    get:
      summary: Get a List of All Templates
      description: Retrieve a list of all templates in the catalog.
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example:
                  count: 1726
                  next: https://api.getbee.io/v1/catalog/templates/?page=2
                  previous: null
                  results:
                  - categories:
                    - others
                    collections: ''
                    context: free
                    description: ''
                    short_description: ''
                    designer: beefree-team
                    id: empty
                    is_blank: true
                    template_type: email
                    order: '99999999'
                    published_at: '2017-08-28'
                    tags:
                    - black
                    - light
                    - promote
                    - serif
                    - two-column
                    - white
                    thumbnail_large: https://d1oco4z2z1fhwp.cloudfront.net/templates/default/1_large.jpg
                    thumbnail: https://d1oco4z2z1fhwp.cloudfront.net/templates/default/1.jpg
                    title: Empty
                  - categories:
                    - others
                    collections: ''
                    context: free
                    description: ''
                    short_description: ''
                    designer: beefree-team
                    id: empty-page
                    is_blank: true
                    template_type: page
                    order: '99999998'
                    published_at: '2021-07-19'
                    tags: []
                    thumbnail_large: https://d1oco4z2z1fhwp.cloudfront.net/templates/default/4246_large.jpg
                    thumbnail: https://d1oco4z2z1fhwp.cloudfront.net/templates/default/4246.jpg
                    title: Empty Page
                  facets:
                    categories:
                    - id: events
                      name: Events
                      parent: usage
                      count: 353
                    - id: seasonal-promotion
                      name: Seasonal Promotion
                      parent: seasonal
                      count: 345
                    - id: e-commerce
                      name: E-commerce
                      parent: industry
                      count: 316
        '400':
          description: Bad request. The request could not be understood or was missing
            required parameters.
        '401':
          description: Unauthorized. Authentication is required and has failed or
            has not been provided.
        '403':
          description: Forbidden. The request was valid, but the server is refusing
            action.
        '500':
          description: Internal Server Error. An unexpected condition was encountered.