openapi: 3.0.0
info:
  title: Get a List of Designers
  description: Get a list of designers from the catalog.
  version: 1.0.0
servers:
- url: https://api.getbee.io
  description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Enter Dev Console API Key as Bearer token
paths:
  /v1/catalog/designers:
    get:
      summary: Get a List of Designers
      description: Get a list of designers from the catalog.
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example:
                  count: 34
                  next: null
                  previous: null
                  results:
                  - available: true
                    avatar_url: https://d1oco4z2z1fhwp.cloudfront.net/designers/LuanaLiguori.png
                    base: Naples, Italy (GMT+2)
                    description: Hello, I'm Luana, a graphic and web designer with
                      8+ years of experience, specializing in email and landing page
                      design. My approach is marked by precision, proactive problem-solving,
                      and strong collaboration. I create visually impactful designs
                      that align with marketing strategies, including social media
                      graphics, blog covers, and presentations. I also offer custom
                      design services tailored to clients' unique needs.
                    short_description: ''
                    display_name: Luana Liguori
                    email: luana0569@gmail.com
                    first_name: Luana
                    highlighted: false
                    hobby: ''
                    id: luana-liguori
                    last_name: Liguori
                    position: Beefree In-House Designer
                    social_behance: ''
                    social_dribbble: ''
                    social_linkedin: ''
                    website: https://www.ilas.com/portfolio/20538400/luana-liguori
        '400':
          description: Bad request. The request could not be understood or was missing
            required parameters.
        '401':
          description: Unauthorized. Authentication is required and has failed or
            has not been provided.
        '403':
          description: Forbidden. The request was valid, but the server is refusing
            action.
        '500':
          description: Internal Server Error. An unexpected condition was encountered.