openapi: 3.0.0
info:
  title: Get a List of Collections
  description: Get a list of collections from the catalog.
  version: 1.0.0
servers:
- url: https://api.getbee.io
  description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Enter Dev Console API Key as Bearer token
paths:
  /v1/catalog/collections:
    get:
      summary: Get a List of Collections
      description: Get a list of collections from the catalog.
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example:
                  count: 19
                  next: https://api.getbee.io/v1/catalog/collections?page=2&pagesize=10
                  previous: null
                  results:
                  - bg_color: '#E8F8D4'
                    description: A Beefree collection is a set of templates focused
                      on a specific communication need. Whether you need to create
                      an automated email sequence to onboard new customers, launch
                      a new product, or dress up transactional messages for your online
                      store, Beefree collections will help you hit the ground running
                      and achieve your goals faster.
                    short_description: ''
                    fg_color: '#140244'
                    highlighted: false
                    icon_url: https://d1oco4z2z1fhwp.cloudfront.net/collections/real-estate_icon.svg
                    id: real-estate
                    image_url: https://d1oco4z2z1fhwp.cloudfront.net/collections/Real-Estate-TC.png
                    name: Real Estate
                    order: '0'
        '400':
          description: Bad request. The request could not be understood or was missing
            required parameters.
        '401':
          description: Unauthorized. Authentication is required and has failed or
            has not been provided.
        '403':
          description: Forbidden. The request was valid, but the server is refusing
            action.
        '500':
          description: Internal Server Error. An unexpected condition was encountered.