openapi: 3.0.0
info:
  title: Beefree SDK HTML to JSON Converter API
  description: Use this API to convert HTML email templates to Beefree's native JSON format. This API provides endpoints to submit conversion jobs, check job statuses, and cancel in-progress jobs.
  version: 1.0.0
servers:
  - url: https://api.getbee.io/v1
    description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Enter Dev Console API Key as Bearer token
  schemas:
    HTML2JsonResponse:
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: string
          description: The unique identifier for the conversion job.
          example: "html_hash_id"
        status:
          type: string
          description: The current status of the job, such as 'success' or 'in-progress'.
          example: "success"
paths:
  /conversion/html-to-json/job:
    post:
      summary: Convert HTML to JSON
      operationId: convert_html_to_json
      description: Submit an HTML document to be converted into Beefree's JSON format. This creates an asynchronous conversion job.
      security:
        - bearerAuth: []
      parameters:
        - name: webhook
          in: query
          description: Optional webhook URL to receive job status updates when the conversion is complete.
          required: false
          schema:
            type: string
      requestBody:
        required: true
        description: HTML content to be converted to JSON
        content:
          text/html:
            schema:
              type: string
              description: The HTML content to be converted
              example: "<html><b>Hello World</b></html>"
      responses:
        '200':
          description: Conversion completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTML2JsonResponse'
        '202':
          description: Conversion job created successfully, processing is in progress.
        '400':
          description: Invalid request. Check the input data.
      examples:
        NodeJS:
          summary: HTML to JSON Conversion in NodeJS
          value: |
            const response = await fetch('https://api.getbee.io/v1/conversion/html-to-json/job', {
              method: 'POST',
              headers: { 'Content-Type': 'text/html', 'Authorization': 'Bearer <token>' },
              body: "<html><b>Hello World</b></html>",
            });
            const jsonResponse = await response.json();
            console.log(jsonResponse);  // Log JSON response
  /conversion/html-to-json/job/{html_hash_id}:
    get:
      summary: Check Conversion Job Status
      operationId: get_html_to_json_job_status
      description: Retrieve the status of an HTML-to-JSON conversion job using its unique HTML hash ID, or get the job result if it's completed.
      security:
        - bearerAuth: []
      parameters:
        - name: html_hash_id
          in: path
          description: The unique identifier for the HTML-to-JSON conversion job.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job completed successfully, and the conversion result is available.
          content:
            application/json:
              example:
                page:
                  body:
                    container:
                      style:
                        background-color: "#FFFFFF"
                    content:
                      computedStyle:
                        linkColor: "#0068A5"
                        messageBackgroundColor: "transparent"
                        messageWidth: "83px"
                      style:
                        color: "#000000"
                        font-family: "Arial, Helvetica Neue, Helvetica, sans-serif"
                  webFonts: []
                  description: ""
                  rows:
                    - columns:
                        - grid-columns: 12
                          modules:
                            - descriptor:
                                computedStyle:
                                  hideContentOnDesktop: false
                                  hideContentOnMobile: false
                                paragraph:
                                  computedStyle:
                                    linkColor: "#FFFFFF"
                                  html: "<p><b>Hello World</b></p>"
                                  style:
                                    color: "#000000"
                                    direction: "ltr"
                                    font-family: "'Times New Roman'"
                                    font-size: "16px"
                                    font-weight: "700"
                                    letter-spacing: "0px"
                                    line-height: "normal"
                                    text-align: "start"
                                style:
                                  padding-bottom: "0px"
                                  padding-left: "0px"
                                  padding-right: "0px"
                                  padding-top: "0px"
                              locked: false
                              type: "mailup-bee-newsletter-modules-paragraph"
                              uuid: "2ed2a760-c5ba-4f77-a60c-c89d2be6a8f2"
                          style:
                            background-color: "#00000000"
                            padding-bottom: "0px"
                            padding-left: "0px"
                            padding-right: "0px"
                            padding-top: "8px"
                          uuid: "55e084e2-319d-4877-b1c4-55035b0f9624"
                      container:
                        style:
                          background-color: "transparent"
                          background-image: "none"
                          background-position: "top left"
                          background-repeat: "no-repeat"
                      content:
                        computedStyle:
                          hideContentOnDesktop: false
                          hideContentOnMobile: false
                          rowColStackOnMobile: true
                          rowReverseColStackOnMobile: false
                          verticalAlign: "top"
                        style:
                          background-color: "transparent"
                          background-image: "none"
                          background-position: "top left"
                          background-repeat: "no-repeat"
                          color: "#000000"
                          width: "500px"
                      empty: false
                      locked: false
                      synced: false
                      type: ""
                      uuid: "1595c545-745d-4c00-84e0-5246b81f7dfe"
                  template:
                    version: "2.0.0"
                  title: ""
        '202':
          description: Job is still being processed.
        '404':
          description: No job found with the specified HTML hash ID.
        '422':
          description: The job failed or the request contains invalid input.
    delete:
      summary: Cancel Conversion Job
      operationId: cancel_html_to_json_job
      description: Cancel an ongoing HTML-to-JSON conversion job by its unique HTML hash ID.
      security:
        - bearerAuth: []
      parameters:
        - name: html_hash_id
          in: path
          description: The unique identifier for the HTML-to-JSON conversion job.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The conversion job was successfully canceled.
        '404':
          description: No in-progress job found with the specified HTML hash ID.
  /conversion/html-to-json/:
    post:
      summary: Convert HTML to JSON in a single API request
      operationId: convert_html_to_json_new
      description: Submit an HTML document to be converted into Beefree's JSON format. This returns the file ready to be loaded in Beefree editor.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: HTML content to be converted to JSON
        content:
          text/html:
            schema:
              type: string
              description: The HTML content to be converted
              example: "<html><b>Hello World</b></html>"
      responses:
        '200':
          description: Conversion completed successfully, and the response body is the Beefree JSON formatted file.
          content:
            application/json:
              example:
                page:
                  body:
                    container:
                      style:
                        background-color: "#FFFFFF"
                    content:
                      computedStyle:
                        linkColor: "#0068A5"
                        messageBackgroundColor: "transparent"
                        messageWidth: "83px"
                      style:
                        color: "#000000"
                        font-family: "Arial, Helvetica Neue, Helvetica, sans-serif"
                  webFonts: []
                  description: ""
                  rows:
                    - columns:
                        - grid-columns: 12
                          modules:
                            - descriptor:
                                computedStyle:
                                  hideContentOnDesktop: false
                                  hideContentOnMobile: false
                                paragraph:
                                  computedStyle:
                                    linkColor: "#FFFFFF"
                                  html: "<p><b>Hello World</b></p>"
                                  style:
                                    color: "#000000"
                                    direction: "ltr"
                                    font-family: "'Times New Roman'"
                                    font-size: "16px"
                                    font-weight: "700"
                                    letter-spacing: "0px"
                                    line-height: "normal"
                                    text-align: "start"
                                style:
                                  padding-bottom: "0px"
                                  padding-left: "0px"
                                  padding-right: "0px"
                                  padding-top: "0px"
                              locked: false
                              type: "mailup-bee-newsletter-modules-paragraph"
                              uuid: "2ed2a760-c5ba-4f77-a60c-c89d2be6a8f2"
                          style:
                            background-color: "#00000000"
                            padding-bottom: "0px"
                            padding-left: "0px"
                            padding-right: "0px"
                            padding-top: "8px"
                          uuid: "55e084e2-319d-4877-b1c4-55035b0f9624"
                      container:
                        style:
                          background-color: "transparent"
                          background-image: "none"
                          background-position: "top left"
                          background-repeat: "no-repeat"
                      content:
                        computedStyle:
                          hideContentOnDesktop: false
                          hideContentOnMobile: false
                          rowColStackOnMobile: true
                          rowReverseColStackOnMobile: false
                          verticalAlign: "top"
                        style:
                          background-color: "transparent"
                          background-image: "none"
                          background-position: "top left"
                          background-repeat: "no-repeat"
                          color: "#000000"
                          width: "500px"
                      empty: false
                      locked: false
                      synced: false
                      type: ""
                      uuid: "1595c545-745d-4c00-84e0-5246b81f7dfe"
                  template:
                    version: "2.0.0"
                  title: ""
        '500':
          description: Conversion failed
      examples:
        NodeJS:
          summary: HTML to JSON Conversion in NodeJS
          value: |
            const response = await fetch('https://api.getbee.io/v1/conversion/html-to-json/job', {
              method: 'POST',
              headers: { 'Content-Type': 'text/html', 'Authorization': 'Bearer <token>' },
              body: "<html><b>Hello World</b></html>",
            });
            const jsonResponse = await response.json();
            console.log(jsonResponse);  // Log JSON response
