openapi: 3.0.0
info:
  title: Transform HTML into an Image
  description: Use this endpoint to transform a design's HTML into an Image, which
    can be used for thumbnails and  similar purposes. Compatible with Email and Page
    builder.
  version: 1.0.0
servers:
- url: https://api.getbee.io
  description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Enter Dev Console API Key as Bearer token
paths:
  /v1/{collection}/image:
    post:
      summary: Transform HTML into an Image
      description: Use this endpoint to transform a design's HTML into an Image, which
        can be used for thumbnails and  similar purposes. Compatible with Email and
        Page builder.
      security:
      - bearerAuth: []
      parameters:
      - name: collection
        in: path
        required: true
        description: The collection ID or name
        schema:
          type: string
      requestBody:
        required: true
        description: Request body for the endpoint
        content:
          application/json:
            schema:
              type: object
              properties:
                file_type:
                  type: string
                  description: A string field for file_type
                  example: png
                size:
                  type: string
                  description: A string field for size
                  example: '1000'
                html:
                  type: string
                  description: A string field for html
                  example: "<html>Hello World!</html>"
      responses:
        '200':
          description: Successful response
          content:
            image/png:
              schema:
                type: string
                example: https://s3.example.com/generic-image.png
        '400':
          description: Bad request. The request could not be understood or was missing
            required parameters.
        '401':
          description: Unauthorized. Authentication is required and has failed or
            has not been provided.
        '403':
          description: Forbidden. The request was valid, but the server is refusing
            action.
        '500':
          description: Internal Server Error. An unexpected condition was encountered.