openapi: 3.0.0
info:
  title: Merge
  description: Replace content
  version: 1.0.0
servers:
  - url: https://api.getbee.io
    description: Base URL for the API
paths:
  /merge:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                replace:
                  type: array
                  items:
                    type: object
                    properties:
                      path:
                        type: string
                      value:
                        type: object
                        properties:
                          columns:
                            type: array
                            items:
                              type: object
                              properties:
                                grid-columns:
                                  type: integer
                                modules:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      descriptor:
                                        type: object
                                        properties:
                                          computedStyle:
                                            type: object
                                          image:
                                            type: object
                                          paragraph:
                                            type: object
                                            description: Content for paragraphs.
                                      type:
                                        type: string
                                    required:
                                      - descriptor
                                      - type
                                style:
                                  type: object
                          container:
                            type: object
                          content:
                            type: object
                          metadata:
                            type: object
                          type:
                            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  html:
                    type: string
                  json:
                    type: object
                    properties:
                      page:
                        type: object
                        properties:
                          body:
                            type: object
                          rows:
                            type: array
                            items:
                              type: object
                          template:
                            type: object
                          title:
                            type: string
                      comments:
                        type: object
        400:
          description: Invalid request
