info:
  description: The API transforms HTML and PDF settings to a JSON object with a URL
    for the PDF document.
  title: PDF Generation API
  version: 1.0.0
openapi: 3.0.0
servers:
  - url: https://api.getbee.io
    description: Base URL for the API
paths:
  /v1/{collection}/pdf:
    post:
      description: This endpoint accepts HTML and settings to generate a PDF document
        and provides a URL for the PDF.
      requestBody:
        content:
          application/json:
            example:
              html: '<!DOCTYPE html><html lang=''en''><head><meta charset=''UTF-8''><title>PDF
                Output</title></head><body style=''font-family: Arial, sans-serif;''><header
                style=''text-align: center; margin-top: 20px;''><h1 style=''font-size:
                36px; color: #4CAF50;''>The Incredible World of Cats</h1></header><main
                style=''margin: 40px;''><p style=''font-size: 18px; line-height: 1.6;''>Cats
                are truly fascinating creatures. With their graceful movements, independent
                nature, and affectionate demeanor, they have captivated humans for
                thousands of years. From their ability to land on their feet to their
                purring, which provides comfort to both themselves and humans, cats
                continue to amaze us with their behavior and quirks. Whether they
                are lounging in the sun or chasing a toy, cats bring joy, companionship,
                and mystery into our lives.</p></main></body></html>'
              page_orientation: landscape
              page_size: Full
            schema:
              properties:
                file_type:
                  default: PDF
                  description: The file type for the output.
                  enum:
                  - PDF
                  type: string
                html:
                  description: A full HTML document to be transformed into a PDF.
                  type: string
                page_orientation:
                  default: landscape
                  description: The orientation of the PDF page.
                  enum:
                  - landscape
                  - portrait
                  type: string
                page_size:
                  default: letter
                  description: The size of the PDF page.
                  enum:
                  - letter
                  - A4
                  - A3
                  - Full
                  type: string
              required:
              - html
              - page_size
              - page_orientation
              - file_type
              type: object
        description: Parameters required to generate a PDF from HTML.
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                body:
                  content_type: application/pdf
                  filename: 7qMsRsxTz8.pdf
                  page_orientation: landscape
                  page_size: Full
                  url: https://pro-bee-beepro-pdf.s3.amazonaws.com/public/pdf/7qMsRsxTz8.pdf
                statusCode: 200
              schema:
                properties:
                  body:
                    properties:
                      content_type:
                        description: The MIME type of the PDF file.
                        type: string
                      filename:
                        description: The filename of the generated PDF.
                        type: string
                      page_orientation:
                        description: The orientation of the PDF.
                        type: string
                      page_size:
                        description: The size of the generated PDF.
                        type: string
                      url:
                        description: The URL where the generated PDF is temporarily
                          hosted.
                        type: string
                    type: object
                  statusCode:
                    description: The HTTP status code of the response.
                    type: integer
                type: object
          description: A successful response with the PDF document URL.
        '400':
          description: Invalid input or request parameters.
      summary: Generate PDF
