components: {}
info:
  description: API for transforming HTML and image settings into an image
  title: Image Transformation API
  version: 1.0.0
openapi: 3.0.0
servers:
  - url: https://api.getbee.io/v1/{collection}
    description: Base URL for the API
paths:
  /v1/{collection}/image:
    post:
      description: Transform HTML and image settings into an image.
      parameters:
      - description: The collection ID or name
        in: path
        name: collection
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              file_type: png
              html: <!DOCTYPE html><html lang='en'><head><meta charset='utf-8'><title>Simple
                HTML</title></head><body><h1>Hello World!</h1><p>This is a simple
                HTML response.</p></body></html>
              size: '1000'
            schema:
              properties:
                file_type:
                  description: Accepts jpg or png
                  type: string
                height:
                  description: The image height in pixels
                  type: integer
                html:
                  description: A Beefree HTML message
                  type: string
                size:
                  description: Image size if width and height are not defined
                  type: string
                width:
                  description: The image width in pixels
                  type: integer
              required:
              - html
              - file_type
              type: object
        description: JSON payload with HTML message and image settings
        required: true
      responses:
        '200':
          content:
            application/octet-stream:
              example: "\uFFFDPNG..."
          description: The image response as a binary data
      summary: Transform HTML to Image
