components: {}
info:
  description: API for indexing rows from a Beefree template
  title: Index Rows API
  version: 1.0.0
openapi: 3.0.0
servers:
  - url: https://api.getbee.io/v1/{collection}
    description: Base URL for the API
paths:
  /v1/{collection}/merge/index:
    post:
      description: Reference an array of metadata objects from a Beefree template in JSON format.              
      parameters:
      - description: The collection ID or name
        in: path
        name: collection
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              source:
                page:
                  body:
                    container:
                      style:
                        background-color: '#FFFFFF'
                    content:
                      computedStyle:
                        linkColor: '#FF819C'
                        messageBackgroundColor: transparent
                        messageWidth: 675px
                      style:
                        color: '#000000'
                        font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif
                    type: mailup-bee-page-properties
                    webFonts:
                    - fontFamily: '''Montserrat'', ''Trebuchet MS'', ''Lucida Grande'',
                        ''Lucida Sans Unicode'', ''Lucida Sans'', Tahoma, sans-serif'
                      name: Montserrat
                      url: https://fonts.googleapis.com/css?family=Montserrat
                  description: BF-ecommerce-template
                  rows:
                  - columns:
                    - grid-columns: 6
                      modules:
                      - descriptor:
                          computedStyle:
                            class: center fixedwidth
                            width: 338
                          image:
                            alt: Image
                            href: https://beefree.io
                            src: https://d1oco4z2z1fhwp.cloudfront.net/templates/default/113/logo_1.png
                          style:
                            padding-bottom: 0px
                            padding-left: 15px
                            padding-right: 15px
                            padding-top: 5px
                            width: 100%
                        locked: false
                        type: mailup-bee-newsletter-modules-image
                      - descriptor:
                          computedStyle:
                            align: center
                            hideContentOnMobile: true
                          divider:
                            style:
                              border-top: 0px solid transparent
                              height: 20px
                              width: 100%
                          style:
                            padding-bottom: 10px
                            padding-left: 10px
                            padding-right: 10px
                            padding-top: 10px
                        locked: false
                        type: mailup-bee-newsletter-modules-divider
                      style:
                        background-color: transparent
                        border-bottom: 0px solid transparent
                        border-left: 0px solid transparent
                        border-right: 0px solid transparent
                        border-top: 0px solid transparent
                        padding-bottom: 0px
                        padding-left: 0px
                        padding-right: 0px
                        padding-top: 30px
                    - grid-columns: 6
                      modules:
                      - descriptor:
                          computedStyle:
                            align: center
                            hideContentOnMobile: true
                          divider:
                            style:
                              border-top: 0px solid transparent
                              height: 32px
                              width: 100%
                          style:
                            padding-bottom: 0px
                            padding-left: 0px
                            padding-right: 0px
                            padding-top: 0px
                        locked: false
                        type: mailup-bee-newsletter-modules-divider
                      - descriptor:
                          computedStyle:
                            hideContentOnMobile: true
                          style:
                            padding-bottom: 15px
                            padding-left: 10px
                            padding-right: 10px
                            padding-top: 0px
                          text:
                            computedStyle:
                              linkColor: '#FF819C'
                            html: '<div class="txtTinyMce-wrapper" style="font-family:
                              Montserrat, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;,
                              &quot;Lucida Sans Unicode&quot;, &quot;Lucida Sans&quot;,
                              Tahoma, sans-serif; font-size: 12px; line-height: 18px;"
                              data-mce-style="font-family: Montserrat, &quot;Trebuchet
                              MS&quot;, &quot;Lucida Grande&quot;, &quot;Lucida Sans
                              Unicode&quot;, &quot;Lucida Sans&quot;, Tahoma, sans-serif;
                              font-size: 12px; line-height: 18px;">

                              <div style="line-height: 18px; font-size: 12px; text-align:
                              center;" data-mce-style="line-height: 18px; font-size:
                              12px; text-align: center;"><span style="font-size: 18px;
                              line-height: 27px;" data-mce-style="font-size: 18px;
                              line-height: 27px;"><strong><span style="line-height:
                              27px; font-size: 18px;" data-mce-style="line-height:
                              27px; font-size: 18px;">ANY DEVICE, ANYWHERE, FAST.</span></strong></span></div>

                              </div>'
                            style:
                              color: '#FFFFFF'
                              font-family: '''Montserrat'', ''Trebuchet MS'', ''Lucida
                                Grande'', ''Lucida Sans Unicode'', ''Lucida Sans'',
                                Tahoma, sans-serif'
                              line-height: 150%
                        locked: false
                        type: mailup-bee-newsletter-modules-text
                      style:
                        background-color: transparent
                        border-bottom: 0px solid transparent
                        border-left: 0px solid transparent
                        border-right: 0px solid transparent
                        border-top: 0px solid transparent
                        padding-bottom: 20px
                        padding-left: 0px
                        padding-right: 0px
                        padding-top: 30px
                    container:
                      style:
                        background-color: '#FF819C'
                        background-image: none
                        background-position: top left
                        background-repeat: no-repeat
                    content:
                      computedStyle:
                        hideContentOnDesktop: false
                        hideContentOnMobile: false
                        rowColStackOnMobile: true
                      style:
                        background-color: transparent
                        background-image: none
                        background-position: top left
                        background-repeat: no-repeat
                        color: '#333'
                        width: 675px
                    locked: false
                    metadata:
                      guid: test3
                      name: demo3
                    type: two-columns-empty
                  template:
                    name: template-base
                    type: basic
                    version: 2.0.0
                  title: BF-ecommerce-template
            schema:
              properties:
                source:
                  description: A Beefree template in JSON format
                  type: object
              required:
              - source
              type: object
        description: JSON payload containing the Beefree template
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
              - guid: test3
                name: demo3
          description: An array of metadata objects containing row details
      summary: Index Rows
