info:
  description: The endpoint accepts a JSON template and returns a plain text document.
  title: Plain Text API
  version: 1.0.0
servers:
  - url: https://api.getbee.io/v1/{collection}
    description: Base URL for the API
openapi: 3.0.0
paths:
  /v1/message/plain-text:
    post:
      description: This endpoint accepts a JSON template to create a plain text version
        of an email.
      requestBody:
        content:
          application/json:
            example:
              language: it-IT
              page:
                body:
                  container:
                    style:
                      background-color: '#fff'
                      background-image: none
                      background-position: top left
                      background-repeat: no-repeat
                      background-size: auto
                  content:
                    computedStyle:
                      linkColor: '#8a3b8f'
                      messageBackgroundColor: transparent
                      messageWidth: 650px
                    style:
                      color: '#000000'
                      font-family: Lato, Tahoma, Verdana, Segoe, sans-serif
                description: ''
                rows:
                - columns:
                  - grid-columns: 12
                    modules:
                    - descriptor:
                        computedStyle:
                          align: center
                          hideContentOnMobile: false
                        divider:
                          style:
                            border-top: 0px solid transparent
                            height: 10px
                            width: 100%
                        style:
                          padding-bottom: 0px
                          padding-left: 0px
                          padding-right: 0px
                          padding-top: 0px
                      locked: false
                      type: mailup-bee-newsletter-modules-divider
                      uuid: b89c3d25-dbec-439a-8ad1-4939a28678e9
                    style:
                      background-color: transparent
                      border-bottom: 0px solid transparent
                      border-left: 0px solid transparent
                      border-right: 0px solid transparent
                      border-top: 0px solid transparent
                      padding-bottom: 0px
                      padding-left: 0px
                      padding-right: 0px
                      padding-top: 0px
                    uuid: 3bd72010-5175-4326-b848-8beacea852d6
                  container:
                    style:
                      background-color: '#8a3b8f'
                      background-image: none
                      background-position: top left
                      background-repeat: no-repeat
                  content:
                    computedStyle:
                      hideContentOnDesktop: false
                      hideContentOnMobile: false
                      rowColStackOnMobile: true
                      rowReverseColStackOnMobile: false
                      verticalAlign: top
                    style:
                      background-color: transparent
                      background-image: none
                      background-position: top left
                      background-repeat: no-repeat
                      color: '#000000'
                      width: 650px
                  empty: false
                  locked: false
                  metadata:
                    category: 625122
                    dateCreated: '2022-01-20T09:49:32.875165Z'
                    dateModified: '2022-01-20T09:49:32.875165Z'
                    description: ''
                    idParent: null
                    name: Pre header purple row
                    slug: pre-header-purple-row
                    uuid: 8b99691b-8e39-47a7-8773-4540cd7ff113
                  synced: false
                  type: one-column-empty
                  uuid: 7fa3e6c4-ac4f-421f-b9eb-db1b9f629fb3
                template:
                  name: template-base
                  type: basic
                  version: 2.0.0
                title: ''
            schema:
              properties:
                language:
                  description: Optional. The output language for multi-language templates.
                  type: string
                page:
                  description: The template's JSON used to create the plain text document.
                  properties:
                    body:
                      properties:
                        container:
                          properties:
                            style:
                              properties:
                                background-color:
                                  type: string
                                background-image:
                                  type: string
                                background-position:
                                  type: string
                                background-repeat:
                                  type: string
                                background-size:
                                  type: string
                              type: object
                          type: object
                        content:
                          properties:
                            computedStyle:
                              properties:
                                linkColor:
                                  type: string
                                messageBackgroundColor:
                                  type: string
                                messageWidth:
                                  type: string
                              type: object
                            style:
                              properties:
                                color:
                                  type: string
                                font-family:
                                  type: string
                              type: object
                          type: object
                      type: object
                    rows:
                      description: Array of row definitions inside the template.
                      type: array
                    template:
                      description: Metadata for the template.
                      type: object
                    title:
                      type: string
                  required:
                  - body
                  - rows
                  - template
                  type: object
              required:
              - page
              type: object
        description: Parameters required to generate plain text from a template.
        required: true
      responses:
        '200':
          content:
            text/plain:
              example: "[BEE Pro Logo](https://beefree.io/) \n\n*****************************\n\
                \nHi \U0001F642 **Would you be interested to participate in a user\
                \ research project with us?**"
              schema:
                type: string
          description: A successful response with the plain text document.
        '400':
          description: Invalid input or request parameters.
      summary: Generate Plain Text
