info:
  contact: {}
  title: 'Beefree SDK: Content Services API'
  version: '1.0'
openapi: 3.0.0
paths:
  /v1/message/merge:
    post:
      consumes:
      - application/json
      deprecated: false
      operationId: /merge
      parameters:
      - default: Bearer {token}
        in: header
        name: Authorization
        required: false
        type: string
      - description: ''
        in: header
        name: Accept
        required: true
        type: string
      - description: ''
        enum:
        - application/json
        in: header
        name: Content-Type
        required: false
        type: string
      - description: ''
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/~1mergerequest'
      produces:
      - application/json
      requestBody:
        content:
          application/json:
            schema:
              properties:
                replace:
                  items:
                    properties:
                      path:
                        description: A JSON Path to the matching nodes in the source
                          JSON.
                        required: true
                        type: string
                      value:
                        description: The value can be an object, such as a saved row.
                          Or, it can be a string, such a hex color code. The value
                          should be the same type as the value you want to match in
                          your match expression.
                        required: true
                        type:
                        - string
                        - object
                    type: object
                  required: true
                  type: array
                source:
                  description: A Beefree template in JSON format.
                  required: true
                  type: object
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  html:
                    description: The HTML message.
                    required: true
                    type: string
                  json:
                    description: The updated Beefree template in JSON format. In the
                      event of an error, the original source is returned.
                    required: true
                    type: object
                  warnings:
                    description: An array of objects containing information about
                      issues that occurred during the merge. If no warnings exist,
                      then it is safe to save the updated JSON.
                    required: false
                    type: array
                type: object
      summary: Replace a Beefree template in JSON format. 
      tags:
      - Misc
