info:
  description: API for retrieving a list of all synced rows inside a template with
    their corresponding rowIdentifier values.
  title: Synced Rows API
  version: 1.0.0
openapi: 3.0.0
servers:
  - url: https://api.getbee.io
    description: Base URL for the API
paths:
  /v1/{collection}/synced-rows:
    post:
      description: Retrieve a list of synced rows from a template.
      parameters:
      - description: The collection name.
        in: path
        name: collection
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              rowIdentifierLabel: guid
              template:
                page:
                  body:
                    container:
                      style:
                        background-color: '#ffffff'
                    content:
                      computedStyle:
                        linkColor: '#7747FF'
                        messageBackgroundColor: transparent
                        messageWidth: 600px
                      style:
                        color: '#000000'
                        font-family: Arial, Helvetica, sans-serif
                    type: mailup-bee-page-properties
                    webFonts:
                    - fontFamily: '''Alegreya'', ''Trebuchet MS'', Helvetica, sans-serif'
                      name: Alegreya
                      url: https://fonts.googleapis.com/css2?family=Alegreya:wght@100;200;300;400;500;600;700;800;900
                  description: ''
                  rows:
                  - columns:
                    - grid-columns: 12
                      modules:
                      - descriptor:
                          computedStyle:
                            hideContentOnAmp: false
                            hideContentOnDesktop: false
                            hideContentOnHtml: false
                            hideContentOnMobile: false
                          paragraph:
                            computedStyle:
                              linkColor: '#7747FF'
                              paragraphSpacing: 16px
                            html: <p>I'm a new paragraph block.</p>
                            style:
                              color: '#101112'
                              direction: ltr
                              font-family: '''Alegreya'', ''Trebuchet MS'', Helvetica,
                                sans-serif'
                              font-size: 16px
                              font-weight: '400'
                              letter-spacing: 0px
                              line-height: 120%
                              text-align: left
                          style:
                            padding-bottom: 10px
                            padding-left: 10px
                            padding-right: 10px
                            padding-top: 10px
                        locked: false
                        type: mailup-bee-newsletter-modules-paragraph
                        uuid: 29cd2a3d-fd76-4537-a91b-b8cb9872d8a3
                      - descriptor:
                          computedStyle:
                            hideContentOnAmp: false
                            hideContentOnDesktop: false
                            hideContentOnHtml: false
                            hideContentOnMobile: false
                          paragraph:
                            computedStyle:
                              linkColor: '#7747FF'
                              paragraphSpacing: 16px
                            html: <p>I'm a new paragraph block.</p>
                            style:
                              color: '#101112'
                              direction: ltr
                              font-family: '''Arvo'', ''Courier New'', Courier, monospace'
                              font-size: 16px
                              font-weight: '400'
                              letter-spacing: 0px
                              line-height: 120%
                              text-align: left
                          style:
                            padding-bottom: 10px
                            padding-left: 10px
                            padding-right: 10px
                            padding-top: 10px
                        locked: false
                        type: mailup-bee-newsletter-modules-paragraph
                        uuid: e22bd20c-805e-439a-832c-f7a100dcaaf2
                      style:
                        background-color: transparent
                        border-bottom: 0px solid transparent
                        border-left: 0px solid transparent
                        border-right: 0px solid transparent
                        border-top: 0px solid transparent
                        padding-bottom: 5px
                        padding-left: 0px
                        padding-right: 0px
                        padding-top: 5px
                      uuid: 56119ad2-574d-4122-8dd1-c1152b5f4879
                    container:
                      style:
                        background-color: transparent
                        background-image: none
                        background-position: top left
                        background-repeat: no-repeat
                    content:
                      computedStyle:
                        hideContentOnDesktop: false
                        hideContentOnMobile: false
                        rowColStackOnMobile: true
                        rowReverseColStackOnMobile: false
                        verticalAlign: top
                      style:
                        background-color: transparent
                        background-image: none
                        background-position: top left
                        background-repeat: no-repeat
                        color: '#000000'
                        width: 600px
                    empty: false
                    locked: false
                    metadata:
                      guid: 0922fb70-f97e-4ae8-bcfe-0be9fd09a0d5
                    synced: true
                    type: one-column-empty
                    uuid: 0922fb70-f97e-4ae8-bcfe-0be9fd09a0d5
                  template:
                    name: template-base
                    type: basic
                    version: 2.0.0
                  title: ''
              webFonts:
              - fontFamily: '''Arvo'', ''Courier New'', Courier, monospace'
                name: Arvo
                url: https://fonts.googleapis.com/css2?family=Arvo:wght@100;200;300;400;500;600;700;800;900
              - fontFamily: '''Alegreya'', ''Trebuchet MS'', Helvetica, sans-serif'
                name: Alegreya
                url: https://fonts.googleapis.com/css2?family=Alegreya:wght@100;200;300;400;500;600;700;800;900
              - fontFamily: '''Chivo'', Arial, Helvetica, sans-serif'
                name: Chivo
                url: https://fonts.googleapis.com/css2?family=Chivo:wght@100;200;300;400;500;600;700;800;900
            schema:
              properties:
                rowIdentifierLabel:
                  description: The label used for identifying the rows added to the
                    metadata key, usually GUID.
                  type: string
                template:
                  description: The JSON structure of the template.
                  type: array
              required:
              - rowIdentifierLabel
              - template
              type: object
        description: Parameters for the synced rows request.
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                syncedRows:
                - rowIdentifier: 0922fb70-f97e-4ae8-bcfe-0be9fd09a0d5
                  rowIndex: 0
              schema:
                properties:
                  syncedRows:
                    items:
                      properties:
                        rowIdentifier:
                          description: The unique identifier for the row, typically
                            a GUID.
                          type: string
                        rowIndex:
                          description: The index of the row inside the template.
                          type: integer
                      type: object
                    type: array
                type: object
          description: A successful response with a list of synced rows.
        '400':
          description: Invalid input or request parameters.
      summary: Get Synced Rows
