openapi: 3.0.0
info:
  title: PDF Generation
  description: This API endpoint transforms HTML and PDF settings to a JSON object with a URL for the PDF document.
  version: 1.0.0
servers:
  - url: https://api.getbee.io
    description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Enter Dev Console API Key as Bearer token
paths:
  /v1/{collection}/pdf:
    post:
      summary: Generate PDF
      description: This endpoint accepts HTML and settings to generate a PDF document and provides a URL for the PDF.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: Parameters required to generate a PDF from HTML.
        content:
          application/json:
            schema:
              type: object
              required:
                - html
                - page_size
                - page_orientation
                - file_type
              properties:
                file_type:
                  type: string
                  enum:
                    - PDF
                  default: PDF
                  description: The file type for the output.
                html:
                  type: string
                  description: A full HTML document to be transformed into a PDF.
                page_orientation:
                  type: string
                  enum:
                    - landscape
                    - portrait
                  default: landscape
                  description: The orientation of the PDF page.
                page_size:
                  type: string
                  enum:
                    - letter
                    - A4
                    - A3
                    - Full
                  default: letter
                  description: The size of the PDF page.
            example:
              html: '<!DOCTYPE html><html lang=''en''><head><meta charset=''UTF-8''><title>PDF Output</title></head><body style=''font-family: Arial, sans-serif;''><header style=''text-align: center; margin-top: 20px;''><h1 style=''font-size: 36px; color: #4CAF50;''>The Incredible World of Cats</h1></header><main style=''margin: 40px;''><p style=''font-size: 18px; line-height: 1.6;''>Cats are truly fascinating creatures...</p></main></body></html>'
              page_orientation: landscape
              page_size: Full
      responses:
        '200':
          description: A successful response with the PDF document URL.
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: object
                    properties:
                      content_type:
                        type: string
                        description: The MIME type of the PDF file.
                      filename:
                        type: string
                        description: The filename of the generated PDF.
                      page_orientation:
                        type: string
                        description: The orientation of the PDF.
                      page_size:
                        type: string
                        description: The size of the generated PDF.
                      url:
                        type: string
                        description: The URL where the generated PDF is temporarily hosted.
                  statusCode:
                    type: integer
                    description: The HTTP status code of the response.
              example:
                body:
                  content_type: application/pdf
                  filename: 7qMsRsxTz8.pdf
                  page_orientation: landscape
                  page_size: Full
                  url: https://pro-bee-beepro-pdf.s3.amazonaws.com/public/pdf/7qMsRsxTz8.pdf
                statusCode: 200
        '400':
          description: Invalid input or request parameters.
      examples:
        NodeJS:
          summary: NodeJS Request Example
          value: |
            const response = await fetch('https://api.getbee.io/v1/{collection}/pdf', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer <token>' },
              body: JSON.stringify({
                "html": "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><title>PDF Output</title></head><body><h1>The Incredible World of Cats</h1><p>Cats are fascinating creatures...</p></body></html>",
                "page_orientation": "landscape",
                "page_size": "Full",
                "file_type": "PDF"
              }),
            });
            const pdfResponse = await response.json();
            console.log(pdfResponse.url); // Log the URL to the generated PDF
