openapi: 3.0.0
info:
  title: Transform HTML into a PDF
  description: Transform email or page HTML into a PDF that can be attached to emails,
    SMS messages, or physically printed out.
  version: 1.0.0
servers:
- url: https://api.getbee.io
  description: Base URL for the API
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Enter Dev Console API Key as Bearer token
paths:
  /v1/{collection}/pdf:
    post:
      summary: Transform HTML into a PDF
      description: Transform email or page HTML into a PDF that can be attached to
        emails, SMS messages, or physically printed out.
      security:
      - bearerAuth: []
      parameters:
      - name: collection
        in: path
        required: true
        description: The collection ID or name
        schema:
          type: string
      requestBody:
        required: true
        description: Request body for the endpoint
        content:
          application/json:
            schema:
              type: object
              properties:
                page_size:
                  type: string
                  description: A string field for page_size
                page_orientation:
                  type: string
                  description: A string field for page_orientation
                html:
                  type: string
                  description: A string field for html
            example:
              page_size: Full
              page_orientation: landscape
              html: '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body><div
                style=''width:900px; margin: 30px;''>test</div></body></html>'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
              example:
                message: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error