components:
  securitySchemes:
    bearerAuth:
      bearerFormat: Enter Dev Console API Key as Bearer token
      scheme: bearer
      type: http
info:
  description: The endpoint accepts a JSON template and returns a plain text document.
  title: Generate Plain Text
  version: 1.0.0
openapi: 3.0.0
paths:
  /v1/message/plain-text:
    post:
      description: ''
      requestBody:
        content:
          application/json:
            example:
              language: en-US
              page:
                body:
                  container:
                    style:
                      background-color: '#fff'
                      background-image: none
                      background-position: top left
                      background-repeat: no-repeat
                      background-size: auto
                  content:
                    computedStyle:
                      linkColor: '#8a3b8f'
                      messageBackgroundColor: transparent
                      messageWidth: 650px
                    style:
                      color: '#000000'
                      font-family: Lato, Tahoma, Verdana, Segoe, sans-serif
                  type: mailup-bee-page-properties
                  webFonts:
                  - fontFamily: '''Lato'', Tahoma, Verdana, Segoe, sans-serif'
                    name: Lato
                    url: https://fonts.googleapis.com/css?family=Lato
                description: ''
                rows:
                - columns:
                  - grid-columns: 12
                    modules:
                    - descriptor:
                        computedStyle:
                          align: center
                          hideContentOnMobile: false
                        divider:
                          style:
                            border-top: 0px solid transparent
                            height: 10px
                            width: 100%
                        style:
                          padding-bottom: 0px
                          padding-left: 0px
                          padding-right: 0px
                          padding-top: 0px
                      locked: false
                      type: mailup-bee-newsletter-modules-divider
                      uuid: b89c3d25-dbec-439a-8ad1-4939a28678e9
                    style:
                      background-color: transparent
                      border-bottom: 0px solid transparent
                      border-left: 0px solid transparent
                      border-right: 0px solid transparent
                      border-top: 0px solid transparent
                      padding-bottom: 0px
                      padding-left: 0px
                      padding-right: 0px
                      padding-top: 0px
                    uuid: 3bd72010-5175-4326-b848-8beacea852d6
                  container:
                    style:
                      background-color: '#8a3b8f'
                      background-image: none
                      background-position: top left
                      background-repeat: no-repeat
                  content:
                    computedStyle:
                      hideContentOnDesktop: false
                      hideContentOnMobile: false
                      rowColStackOnMobile: true
                      rowReverseColStackOnMobile: false
                      verticalAlign: top
                    style:
                      background-color: transparent
                      background-image: none
                      background-position: top left
                      background-repeat: no-repeat
                      color: '#000000'
                      width: 650px
                  empty: false
                  locked: false
                  metadata:
                    category: 625122
                    dateCreated: '2022-01-20T09:49:32.875165Z'
                    dateModified: '2022-01-20T09:49:32.875165Z'
                    description: ''
                    idParent: null
                    name: Pre-header strategy row
                    slug: pre-header-strategy-row
                    thumb_large: https://pro-bee-beepro-thumbnails.s3.amazonaws.com/templates/saved-rows/53601/655907/example_large.jpg
                    thumb_medium: https://pro-bee-beepro-thumbnails.s3.amazonaws.com/templates/saved-rows/53601/655907/example_medium.jpg
                    thumb_small: https://pro-bee-beepro-thumbnails.s3.amazonaws.com/templates/saved-rows/53601/655907/example_small.jpg
                    uuid: 8b99691b-8e39-47a7-8773-4540cd7ff113
                  synced: false
                  type: one-column-empty
                  uuid: 7fa3e6c4-ac4f-421f-b9eb-db1b9f629fb3
                - columns:
                  - grid-columns: 12
                    modules:
                    - align: left
                      descriptor:
                        computedStyle:
                          class: left fixedwidth
                          width: 162.5px
                        image:
                          alt: Strategy Logo
                          height: 109px
                          href: https://marketingstrategy.io/
                          percWidth: 25
                          prefix: ''
                          src: https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/BeeProAgency/53601_655907/editor_images/Strategy_logo.png
                          target: _self
                          width: 291px
                        style:
                          padding-bottom: 40px
                          padding-left: 20px
                          padding-right: 20px
                          padding-top: 20px
                          width: 100%
                      locked: false
                      type: mailup-bee-newsletter-modules-image
                      uuid: cc54124d-97bd-44e0-b15e-710a577840ec
                    - descriptor:
                        paragraph:
                          computedStyle:
                            linkColor: '#0068a5'
                            paragraphSpacing: 16px
                          html: "<p>Hi there \U0001F642</p>\n<p><strong>Would you\
                            \ be interested in discussing innovative marketing strategies\
                            \ with us?</strong></p>\n<p>We\u2019re organizing a research\
                            \ session via video call, usually lasting 30-45 minutes.\
                            \ We\u2019d love to understand how marketing strategies\
                            \ shape your daily workflow and how we can help streamline\
                            \ it for you.</p>\n<p><strong>Interested?</strong> Please\
                            \ schedule a time that works for you using <a href=\"\
                            https://calendly.com/strategy-meeting\" target=\"_blank\"\
                            \ rel=\"noopener\">this link \u2197</a></p>\n<p>Looking\
                            \ forward to chatting!</p>\n<p>Best regards,</p>\n<p>Jane\
                            \ Doe from the Strategy Team \U0001F49C</p>"
                          style:
                            color: '#000000'
                            direction: ltr
                            font-family: inherit
                            font-size: 14px
                            font-weight: '400'
                            letter-spacing: 0px
                            line-height: 120%
                            text-align: left
                        style:
                          padding-bottom: 10px
                          padding-left: 10px
                          padding-right: 10px
                          padding-top: 10px
                      locked: false
                      type: mailup-bee-newsletter-modules-paragraph
                      uuid: 0456f2de-7125-475c-b016-41f77b3fda47
                    style:
                      background-color: transparent
                      border-bottom: 0px solid transparent
                      border-left: 0px solid transparent
                      border-right: 0px solid transparent
                      border-top: 0px solid transparent
                      padding-bottom: 5px
                      padding-left: 10px
                      padding-right: 10px
                      padding-top: 5px
                    uuid: 61614a04-eb36-4d98-b28e-c6c9e048877d
                  container:
                    style:
                      background-color: transparent
                      background-image: none
                      background-position: top left
                      background-repeat: no-repeat
                  content:
                    computedStyle:
                      hideContentOnDesktop: false
                      hideContentOnMobile: false
                      rowColStackOnMobile: true
                      rowReverseColStackOnMobile: false
                      verticalAlign: top
                    style:
                      background-color: transparent
                      background-image: none
                      background-position: top left
                      background-repeat: no-repeat
                      color: '#000000'
                      width: 650px
                  empty: false
                  locked: false
                  metadata:
                    category: 625122
                    dateCreated: '2022-01-20T09:51:57.896884Z'
                    dateModified: '2022-01-20T09:51:57.896884Z'
                    description: ''
                    idParent: null
                    name: Marketing message
                    slug: marketing-message
                    thumb_large: https://pro-bee-beepro-thumbnails.s3.amazonaws.com/templates/saved-rows/53601/655907/large.jpg
                    thumb_medium: https://pro-bee-beepro-thumbnails.s3.amazonaws.com/templates/saved-rows/53601/655907/medium.jpg
                    thumb_small: https://pro-bee-beepro-thumbnails.s3.amazonaws.com/templates/saved-rows/53601/655907/small.jpg
                    uuid: 35d02430-32b2-41d6-a115-68d7bb476d64
                  synced: false
                  type: two-columns-empty
                  uuid: f57920be-d9e4-41c0-a009-eb85fd2a8034
                template:
                  name: template-strategy
                  type: basic
                  version: 2.0.0
                title: Marketing Strategy
            schema:
              properties:
                language:
                  type: string
                page:
                  type: object
              type: object
        description: Parameters required to generate plain text from a template.
        required: true
      responses:
        '200':
          content:
            text/plain:
              schema:
                type: string
          description: A successful response with the plain text document.
        '400':
          description: Invalid input or request parameters.
      security:
      - bearerAuth: []
      summary: Plain Text 2
servers:
- description: Base URL for the API
  url: https://api.getbee.io
